# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

  # snyk code
  - script: snyk code test --sarif-file-output=CodeAnalysisLogs/snyk-code.sarif
    continueOnError: true
    displayName: 'snyk code'

  # snyk open source
  - script: snyk test --all-projects --sarif-file-output=CodeAnalysisLogs/snyk-open-source.sarif
    continueOnError: true
    displayName: 'snyk open source'

  # snyk container
  # NOTE: Change this to your container name
  - script: snyk container test sebsnyk/juice-shop --file=Dockerfile --sarif-file-output=CodeAnalysisLogs/snyk-container.sarif
    continueOnError: true
    displayName: 'snyk container'

  # snyk iac
  - script: snyk iac test --sarif-file-output=CodeAnalysisLogs/snyk-iac.sarif
    continueOnError: true
    displayName: 'snyk iac'
